/**
 * OSDK 2.0 client/generated split enforcement
 * @owner palantirkc-plugin-codegen
 * @purpose OSDK 2.0 client/generated split enforcement
 */
// palantir-mini v0 — OSDK 2.0 client/generated split enforcement
// Domain: LOGIC (DRY + OCP applied to codegen architecture)
//
// Palantir OSDK 2.0 cleanly separates:
//   - client code (stable public API, hand-written, lives in lib/)
//   - generated code (AUTO-GENERATED, lives in src/generated/, never hand-edited)
//
// This module enforces that separation by:
//   - rejecting writes to lib/ that would collide with generated/
//   - rejecting writes to generated/ that contain non-generated content
//
// Invoked by codegen-runner agent before writing any generated file.

import * as fs from "fs";
import * as path from "path";

export interface SplitPolicy {
  clientRoot:    string;  // hand-written code root
  generatedRoot: string;  // auto-generated code root
  generatedMarker: string; // required file header to identify generated files
}

const DEFAULT_MARKER = "// AUTO-GENERATED by palantir-mini";

export function defaultPolicy(projectRoot: string): SplitPolicy {
  return {
    clientRoot:      path.join(projectRoot, "src"),
    generatedRoot:   path.join(projectRoot, "src", "generated"),
    generatedMarker: DEFAULT_MARKER,
  };
}

export interface SplitCheckResult {
  passed:    boolean;
  violations: string[];
}

/**
 * Check that a target write obeys the split policy.
 *
 * Rules:
 * - Writing to generatedRoot/* is only allowed if content starts with generatedMarker.
 * - Writing to clientRoot/* that is NOT under generatedRoot/ is only allowed if
 *   content does NOT start with generatedMarker (clients must not be marked generated).
 */
export function checkSplit(policy: SplitPolicy, filePath: string, content: string): SplitCheckResult {
  const violations: string[] = [];
  const isUnderGenerated = filePath.startsWith(policy.generatedRoot);
  const isUnderClient    = filePath.startsWith(policy.clientRoot);
  const startsWithMarker = content.trimStart().startsWith(policy.generatedMarker);

  if (isUnderGenerated && !startsWithMarker) {
    violations.push(`file under generatedRoot but missing generated marker: ${filePath}`);
  }
  if (isUnderClient && !isUnderGenerated && startsWithMarker) {
    violations.push(`file under clientRoot starts with generated marker (moved wrong): ${filePath}`);
  }

  return {
    passed: violations.length === 0,
    violations,
  };
}

/**
 * Walk the generatedRoot and verify every file has the generated marker.
 * Returns a list of violations. Read-only — does not mutate.
 */
export function auditGeneratedRoot(policy: SplitPolicy): SplitCheckResult {
  const violations: string[] = [];
  if (!fs.existsSync(policy.generatedRoot)) {
    return { passed: true, violations };
  }
  const stack = [policy.generatedRoot];
  while (stack.length > 0) {
    const dir = stack.pop()!;
    let entries: fs.Dirent[] = [];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      const p = path.join(dir, entry.name);
      if (entry.isDirectory()) stack.push(p);
      else if (entry.isFile() && (entry.name.endsWith(".ts") || entry.name.endsWith(".d.ts"))) {
        try {
          const content = fs.readFileSync(p, "utf8");
          if (!content.trimStart().startsWith(policy.generatedMarker)) {
            violations.push(`generated file missing marker: ${path.relative(policy.generatedRoot, p)}`);
          }
        } catch (e) {
          violations.push(`generated file unreadable: ${path.relative(policy.generatedRoot, p)} (${(e as Error).message})`);
        }
      }
    }
  }
  return { passed: violations.length === 0, violations };
}
