/**
 * @stable — PropagationReplayPayload primitive (prim-data-19, v1.34.0)
 *
 * Result envelope of the `propagation_audit_backward` MCP handler. A
 * BackwardProp replay seeds at a single events.jsonl row and walks the
 * 5-dimensional Decision Lineage (when, atopWhich, throughWhich, byWhom,
 * withWhat) backward across the ForwardProp authority chain to identify
 * the earliest step where any dimension's invariant breaks.
 *
 * Authority chain:
 *   plans/distributed-wishing-manatee.md §Phase 1 + parent
 *     plans/cosmic-hatching-pizza.md §W6
 *       ↓
 *   schemas/ontology/primitives/propagation-audit.ts (PropagationStep SSoT)
 *       ↓
 *   schemas/ontology/primitives/propagation-replay.ts (this file)
 *       ↓
 *   palantir-mini bridge/handlers/propagation-audit-backward.ts (consumer,
 *     Phase 4)
 *
 * D/L/A domain: DATA (audit-result envelope; immutable replay record)
 * @owner palantirkc-ontology
 * @purpose Canonical backward-chain replay result primitive for W6 substrate
 * @authorityChain research → schemas → shared-core → project-ontology → contracts → runtime
 */

import type { PropagationStep } from "./propagation-audit";

/** Re-exported from propagation-audit.ts to keep replay self-contained. */
export type { PropagationStep } from "./propagation-audit";
export { PROPAGATION_STEPS, isPropagationStep } from "./propagation-audit";

/**
 * The 5 Decision Lineage dimensions a backward replay can trace
 * (rule 10 §The 5 dimensions).
 */
export type LineageDimension =
  | "when"
  | "atopWhich"
  | "throughWhich"
  | "byWhom"
  | "withWhat";

/** Single node along the backward replay path. */
export interface PropagationReplayNode {
  /** events.jsonl row id this node corresponds to. */
  readonly eventId: string;
  /**
   * Distance from the seed event measured in propagation steps
   * (0 = seed, 1 = direct ancestor, …).
   */
  readonly propagationDepth: number;
  /** Agent identity that emitted the event (rule 10 byWhom). */
  readonly byWhom: string;
  /** ISO 8601 emission timestamp (rule 10 when). */
  readonly when: string;
}

/**
 * Envelope returned by the `propagation_audit_backward` MCP handler.
 *
 * Walks backward from `seedEventId` along each `tracedDimensions` axis,
 * recording every visited lineage node. `firstViolationStep` flags the
 * earliest authority-chain step where any traced dimension diverged
 * from the recorded invariant; `null` means the replay is fully clean.
 */
export interface PropagationReplayPayload {
  /** Stable id of this replay run (opaque, generated by the handler). */
  readonly replayId: string;
  /** events.jsonl row that seeded the replay. */
  readonly seedEventId: string;
  /**
   * Subset of LineageDimension values traced this run. `[]` is invalid;
   * handlers MUST trace at least one dimension.
   */
  readonly tracedDimensions: readonly LineageDimension[];
  /**
   * Earliest authority-chain step where invariants broke, or `null`
   * when the replay is fully consistent.
   */
  readonly firstViolationStep: PropagationStep | null;
  /** Visited nodes, ordered by ascending `propagationDepth`. */
  readonly lineageNodes: readonly PropagationReplayNode[];
  /** ISO 8601 replay timestamp. */
  readonly replayedAt: string;
}

/**
 * Type guard — narrows an unknown value to PropagationReplayPayload.
 */
export function isPropagationReplayPayload(
  x: unknown,
): x is PropagationReplayPayload {
  if (typeof x !== "object" || x === null) return false;
  const v = x as Record<string, unknown>;
  return (
    typeof v.replayId === "string" &&
    typeof v.seedEventId === "string" &&
    Array.isArray(v.tracedDimensions) &&
    (v.firstViolationStep === null ||
      typeof v.firstViolationStep === "string") &&
    Array.isArray(v.lineageNodes) &&
    typeof v.replayedAt === "string"
  );
}
