/**
 * palantir-mini — Rule primitive (prim-ops-19)
 *
 * Declares a Claude-local overlay rule under ~/.claude/rules/ (or
 * scope-migrated under <project>/.claude/rules/). Drives the
 * `pm_rule_get` / `pm_rule_list` / `pm_rule_search` / `pm_rule_audit`
 * MCP handlers added in R2 (rules-redesign).
 *
 * Authority chain:
 *   research/claude-code/ -> rules/CONTEXT.md (authoring spec §5)
 *   -> schemas/ontology/primitives/rule.ts (this file)
 *   -> ontology/shared-core/ (consumer surface re-export)
 *   -> palantir-mini/bridge/handlers/pm-rule-*.ts (R2b MCP handlers)
 *   -> generated/rule-registry.ts (R2b codegen target)
 *
 * Branded RID pattern (zero runtime cost):
 *   type RuleRid = string & { __brand: "RuleRid" };
 *
 * Frontmatter contract (every rules/NN-*.md file declares these fields;
 * R2b codegen parses frontmatter and emits the registry):
 *
 *   ---
 *   ruleId: <number>              # 01-18 + 0 (CONTEXT); next = 19
 *   slug: <kebab-case>            # e.g. "events-jsonl"
 *   scope: global | plugin:<id> | project:<id>
 *   version: <semver>             # rule-level semver
 *   invariant: "<≤1 sentence>"    # CORE.md inlines this
 *   supersededBy: <ruleId> | null
 *   crossRefs: [<ruleId>, ...]
 *   hookCitations: [<hook-name>, ...]
 *   ---
 *
 * Stability contract (rules/CONTEXT.md §4):
 *   - ruleId is a stable API. Never rename, never recycle.
 *   - Rule 04 is a permanent historical gap.
 *   - Slugs rename under rule-level MAJOR bump + deprecation window.
 *   - Scope migration is one-way (global → plugin or global → project).
 *
 * This file is STABLE CONTRACT. Do not change without a migration plan.
 * @owner palantirkc-ontology
 * @purpose Rule primitive (prim-ops-19)
 */

export type RuleRid = string & {
  readonly __brand: "RuleRid";
};

export const ruleRid = (s: string): RuleRid => s as RuleRid;

/** ruleId is a non-negative integer; 0 reserved for CONTEXT meta-rule, 1-18 current. */
export type RuleId = number;

export type RuleSlug = string;

export type RuleScopeId =
  | "global"
  | `plugin:${string}`
  | `project:${string}`;

/**
 * Hook name citation — each entry is the hook filename stem from
 * `.claude/plugins/palantir-mini/hooks/<name>.ts` (minus extension).
 * Validated at R3 by the `rule-citation-validate` hook.
 */
export type HookCitation = string;

export interface RuleDeclaration {
  /** Stable numeric ID, primary key. */
  ruleId: RuleId;

  /** Human-readable alias. Rename requires rule-level MAJOR bump. */
  slug: RuleSlug;

  /** Where this rule applies. Scope migration is one-way. */
  scope: RuleScopeId;

  /** Rule-level semver (independent from schemas/ semver). */
  version: string;

  /** One-sentence distillation. CORE.md inlines; pm_rule_list returns. */
  invariant: string;

  /** If retired + replaced, points to replacement ruleId. */
  supersededBy: RuleId | null;

  /** If scope-migrated, records the new scope (one-way). */
  scopeMigratedTo?: RuleScopeId | null;

  /** Related rule IDs for `pm_rule_get --with-context` neighbor fetch. */
  crossRefs: readonly RuleId[];

  /** Hooks that cite this rule in blocking messages or code comments. */
  hookCitations: readonly HookCitation[];

  /** Absolute or repo-relative path to the T2 .md file with the full body. */
  bodyPath: string;

  /** ISO8601 timestamp of last edit — used by `rule-drift-detect` hook. */
  lastModified?: string;

  /** Tier classification for load-model enforcement. */
  tier?: "T1" | "T2";

  /** Per-rule body LOC ceiling exception for consolidation-hub rules (default 30 if absent; honored by `pm_rule_audit` bottleneck check). */
  bodyLocCeiling?: number;
}

/**
 * Registry keyed by ruleId. Generated by R2b codegen from rules/*.md
 * frontmatter. Consumers import from ontology/shared-core/ (per rule 08).
 */
export type RuleRegistry = ReadonlyMap<RuleId, RuleDeclaration>;

/** Helper: branded RID constructor from ruleId + scope. */
export function ruleRidFromId(scope: RuleScopeId, id: RuleId): RuleRid {
  return ruleRid(`rid.${scope}.rule.${String(id).padStart(2, "0")}`);
}

/** Audit result shape returned by `pm_rule_audit` MCP handler (R2b). */
export interface RuleAuditFinding {
  kind:
    | "drift:memory-counter"
    | "drift:file-count"
    | "bottleneck:t1-total"
    | "bottleneck:t1-file"
    | "bottleneck:t2-file"
    | "bottleneck:t2-total"
    | "stale-crossref"
    | "stale-hook-citation"
    | "missing-frontmatter"
    | "recycled-rule-id"
    | "unused_rule_30d";
  severity: "advisory" | "warn" | "block";
  ruleId?: RuleId;
  detail: string;
  measured?: number;
  ceiling?: number;
}

/** Scope migration + supersession helpers for `pm_rule_get` follow-through. */
export function isRuleRetired(r: RuleDeclaration): boolean {
  return r.supersededBy !== null && r.supersededBy !== undefined;
}

export function isRuleScopeMigrated(r: RuleDeclaration): boolean {
  return (
    r.scopeMigratedTo !== null &&
    r.scopeMigratedTo !== undefined &&
    r.scopeMigratedTo !== r.scope
  );
}
