#!/usr/bin/env bun
// Generates tests/parity/codex/inventory-shape.fixture.json (ledger row
// A620) — the Codex-side seed for A650's cross-runtime parity suite
// (docs/architecture.md ADR-007, execution-plan DoD item 9). Pure function
// of src/adapters/codex/binding.generated.ts + src/adapters/shared/ — no
// wall-clock input, deterministic. Run: `bun run
// tests/parity/codex/generate-fixture.ts`.
//
// Scope: this row (A620) is Codex-only; src/adapters/{claude,gemini}/ do
// not exist yet, so no cross-runtime comparison is possible here. This
// fixture captures Codex's generated-inventory SHAPE only (capability area
// set, tool-name set, manifest field-key set, flat-schema convention) —
// the part ADR-007 requires to be byte-equivalent across runtimes. It
// deliberately does NOT assert that per-runtime capability VERDICT VALUES
// match (those are legitimate metadata differences per R210 — "Packaging
// differences are adapter metadata only"). A650 (Wave 6, same writer, same
// tree) owns building the actual 3-way byte comparison once
// src/adapters/{claude,gemini}/ exist; this file is its Codex-side input,
// not a self-contained parity proof.

import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { CAPABILITY_AREAS } from "../../../src/adapters/shared";
import { CODEX_BINDING } from "../../../src/adapters/codex";

const FIXTURE_DIR = resolve(import.meta.dir);
const OUTPUT_PATH = join(FIXTURE_DIR, "inventory-shape.fixture.json");

export const HEADER_NOTE =
  "generated by tests/parity/codex/generate-fixture.ts from src/adapters/codex/binding.generated.ts — structural shape only, not a verdict-value parity claim; see tests/parity/codex/README.md";

export interface CodexInventoryShapeFixture {
  readonly note: string;
  readonly runtimeId: "codex";
  readonly capabilityAreas: readonly string[];
  readonly toolNames: readonly string[];
  readonly manifestFieldKeys: readonly string[];
  readonly toolInputSchemaConvention: {
    readonly type: "object";
    readonly requiredKeys: readonly string[];
    readonly additionalProperties: false;
    readonly flat: true;
  };
  readonly sourceOfRecord: string;
}

export function buildCodexInventoryShapeFixture(): CodexInventoryShapeFixture {
  return {
    note: HEADER_NOTE,
    runtimeId: "codex",
    capabilityAreas: [...CAPABILITY_AREAS].sort(),
    toolNames: [...CODEX_BINDING.tools.map((t) => t.name)].sort(),
    manifestFieldKeys: [...Object.keys(CODEX_BINDING.manifest)].sort(),
    toolInputSchemaConvention: {
      type: "object",
      requiredKeys: ["runtime"],
      additionalProperties: false,
      flat: true,
    },
    sourceOfRecord: CODEX_BINDING.sourceOfRecord,
  };
}

function main(): void {
  const fixture = buildCodexInventoryShapeFixture();
  writeFileSync(OUTPUT_PATH, `${JSON.stringify(fixture, null, 2)}\n`, "utf8");
  console.log("tests/parity/codex/generate-fixture.ts — wrote tests/parity/codex/inventory-shape.fixture.json");
}

if (import.meta.main) main();
