#!/usr/bin/env bun
// Generates tests/parity/gemini/inventory-shape.fixture.json (ledger row
// A640) — the Gemini-side seed for A650's cross-runtime parity suite
// (docs/architecture.md ADR-007, execution-plan DoD item 9). Pure function
// of src/adapters/gemini/binding.generated.ts + src/adapters/shared/ — no
// wall-clock input, deterministic. Run: `bun run
// tests/parity/gemini/generate-fixture.ts`. Mirrors
// tests/parity/codex/generate-fixture.ts and tests/parity/claude/generate-
// fixture.ts's exact pattern (A620/A630), plus one Gemini-specific
// addition (`nativePackagingSupported`) documented below.
//
// Scope: this row (A640) adds the Gemini side — the last of the 3 Wave-6
// runtime rows. This fixture captures Gemini's generated-inventory SHAPE
// only (capability area set, tool-name set, manifest field-key set,
// flat-schema convention, native-packaging-supported flag) — the part
// ADR-007 requires to be byte-equivalent (or, for
// `nativePackagingSupported`, explicitly and legitimately per-runtime) —
// across runtimes. It deliberately does NOT assert that per-runtime
// capability VERDICT VALUES match (those are legitimate metadata
// differences per R210 — "Packaging differences are adapter metadata
// only"). A650 (Wave 6, same writer, same tree, depends_on [A640]) owns
// building the actual 3-way byte comparison; this file is its Gemini-side
// input, not a self-contained parity proof.

import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { CAPABILITY_AREAS } from "../../../src/adapters/shared";
import { GEMINI_BINDING } from "../../../src/adapters/gemini";

const FIXTURE_DIR = resolve(import.meta.dir);
const OUTPUT_PATH = join(FIXTURE_DIR, "inventory-shape.fixture.json");

export const HEADER_NOTE =
  "generated by tests/parity/gemini/generate-fixture.ts from src/adapters/gemini/binding.generated.ts — structural shape only, not a verdict-value parity claim; see tests/parity/gemini/README.md";

export interface GeminiInventoryShapeFixture {
  readonly note: string;
  readonly runtimeId: "gemini";
  readonly capabilityAreas: readonly string[];
  readonly toolNames: readonly string[];
  readonly manifestFieldKeys: readonly string[];
  readonly toolInputSchemaConvention: {
    readonly type: "object";
    readonly requiredKeys: readonly string[];
    readonly additionalProperties: false;
    readonly flat: true;
  };
  readonly nativePackagingSupported: boolean;
  readonly sourceOfRecord: string;
}

export function buildGeminiInventoryShapeFixture(): GeminiInventoryShapeFixture {
  return {
    note: HEADER_NOTE,
    runtimeId: "gemini",
    capabilityAreas: [...CAPABILITY_AREAS].sort(),
    toolNames: [...GEMINI_BINDING.tools.map((t) => t.name)].sort(),
    manifestFieldKeys: [...Object.keys(GEMINI_BINDING.manifest)].sort(),
    toolInputSchemaConvention: {
      type: "object",
      requiredKeys: ["runtime"],
      additionalProperties: false,
      flat: true,
    },
    nativePackagingSupported: GEMINI_BINDING.manifest.nativePackaging.supported,
    sourceOfRecord: GEMINI_BINDING.sourceOfRecord,
  };
}

function main(): void {
  const fixture = buildGeminiInventoryShapeFixture();
  writeFileSync(OUTPUT_PATH, `${JSON.stringify(fixture, null, 2)}\n`, "utf8");
  console.log("tests/parity/gemini/generate-fixture.ts — wrote tests/parity/gemini/inventory-shape.fixture.json");
}

if (import.meta.main) main();
