#!/usr/bin/env bun
// Generates tests/parity/claude/inventory-shape.fixture.json (ledger row
// A630) — the Claude-side seed for A650's cross-runtime parity suite
// (docs/architecture.md ADR-007, execution-plan DoD item 9). Pure function
// of src/adapters/claude/binding.generated.ts + src/adapters/shared/ — no
// wall-clock input, deterministic. Run: `bun run
// tests/parity/claude/generate-fixture.ts`. Mirrors
// tests/parity/codex/generate-fixture.ts's exact pattern (A620).
//
// Scope: this row (A630) adds the Claude side; src/adapters/gemini/ does
// not exist yet, so no full 3-way comparison is possible here. This
// fixture captures Claude's generated-inventory SHAPE only (capability
// area set, tool-name set, manifest field-key set, flat-schema convention)
// — the part ADR-007 requires to be byte-equivalent across runtimes. It
// deliberately does NOT assert that per-runtime capability VERDICT VALUES
// match (those are legitimate metadata differences per R210 — "Packaging
// differences are adapter metadata only"). A650 (Wave 6, same writer, same
// tree) owns building the actual 3-way byte comparison once
// src/adapters/gemini/ exists; this file is its Claude-side input, not a
// self-contained parity proof.

import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { CAPABILITY_AREAS } from "../../../src/adapters/shared";
import { CLAUDE_BINDING } from "../../../src/adapters/claude";

const FIXTURE_DIR = resolve(import.meta.dir);
const OUTPUT_PATH = join(FIXTURE_DIR, "inventory-shape.fixture.json");

export const HEADER_NOTE =
  "generated by tests/parity/claude/generate-fixture.ts from src/adapters/claude/binding.generated.ts — structural shape only, not a verdict-value parity claim; see tests/parity/claude/README.md";

export interface ClaudeInventoryShapeFixture {
  readonly note: string;
  readonly runtimeId: "claude";
  readonly capabilityAreas: readonly string[];
  readonly toolNames: readonly string[];
  readonly manifestFieldKeys: readonly string[];
  readonly toolInputSchemaConvention: {
    readonly type: "object";
    readonly requiredKeys: readonly string[];
    readonly additionalProperties: false;
    readonly flat: true;
  };
  readonly sourceOfRecord: string;
}

export function buildClaudeInventoryShapeFixture(): ClaudeInventoryShapeFixture {
  return {
    note: HEADER_NOTE,
    runtimeId: "claude",
    capabilityAreas: [...CAPABILITY_AREAS].sort(),
    toolNames: [...CLAUDE_BINDING.tools.map((t) => t.name)].sort(),
    manifestFieldKeys: [...Object.keys(CLAUDE_BINDING.manifest)].sort(),
    toolInputSchemaConvention: {
      type: "object",
      requiredKeys: ["runtime"],
      additionalProperties: false,
      flat: true,
    },
    sourceOfRecord: CLAUDE_BINDING.sourceOfRecord,
  };
}

function main(): void {
  const fixture = buildClaudeInventoryShapeFixture();
  writeFileSync(OUTPUT_PATH, `${JSON.stringify(fixture, null, 2)}\n`, "utf8");
  console.log("tests/parity/claude/generate-fixture.ts — wrote tests/parity/claude/inventory-shape.fixture.json");
}

if (import.meta.main) main();
