/**
 * Upgrade Scaffold Generator — Consumes UpgradeSpec[] from semantic-audit and
 * generates SCAFFOLD code patches across ontology/*.ts, convex/, and src/ layers.
 *
 * IMPORTANT: This is a SCAFFOLD GENERATOR, not a semantics-preserving transformer.
 * Generated code is a starting point that REQUIRES human review and refinement:
 *   - BilingualDesc fields use apiName as placeholder (not real descriptions)
 *   - Convex type mappings are simplified (e.g., all non-numeric → v.string())
 *   - Generated queries use basic .order("desc").take(N) pattern only
 *   - No validation functions are generated (must be added manually)
 *   - No webhook endpoint implementations are generated
 *   - Property descriptions are not populated from ontology context
 *
 * WI-06 remediation (2026-03-17): Renamed from "Upgrade Apply" to "Upgrade
 * Scaffold Generator" to align name/comments/behavior. Previously described
 * like a semantic upgrader but behaves as a lossy scaffold generator.
 *
 * Usage:
 *   import { auditSemantics } from "~/.claude/schemas/ontology/semantic-audit";
 *   import { generateUpgradeScaffolds } from "~/.claude/schemas/ontology/upgrade-apply";
 *   const report = auditSemantics(ontology);
 *   const patches = generateUpgradeScaffolds(report.upgradeSpecs, "saveticker");
 *   // patches contains SCAFFOLD file paths + code content for each layer
 *   // ALL generated code requires human review before use
 *
 * Output: scaffold patches for 3 layers:
 *   1. ontology/*.ts  — entity/property/mutation additions (placeholder descriptions)
 *   2. convex/        — table + query + mutation stubs (simplified type mapping)
 *   3. src/           — useQuery hook stubs (basic pattern only)
 */

import type { UpgradeSpec } from "./semantic-audit";

// =========================================================================
// Output Types
// =========================================================================

export interface FilePatch {
  readonly filePath: string;
  readonly layer: "ontology" | "convex" | "src";
  readonly operation: "append" | "insert" | "create";
  readonly content: string;
  readonly description: string;
}

export interface UpgradeResult {
  readonly totalSpecs: number;
  readonly appliedSpecs: number;
  readonly skippedSpecs: number;
  readonly patches: readonly FilePatch[];
  readonly convexTableNames: readonly string[];
  readonly summary: string;
}

// =========================================================================
// Code Generators
// =========================================================================

function toCamelPlural(pascalSingular: string): string {
  const first = pascalSingular.charAt(0).toLowerCase() + pascalSingular.slice(1);
  if (first.endsWith("s")) return first;
  if (first.endsWith("y") && !/[aeiou]y$/i.test(pascalSingular)) {
    return first.slice(0, -1) + "ies";
  }
  return first + "s";
}

function generateEntityCode(spec: UpgradeSpec): string {
  const details = spec.details as {
    properties: Array<{ apiName: string; baseType: string; required: boolean; readonly: boolean }>;
    primaryKey: string;
    titleKey: string;
  };

  const propsCode = details.properties.map((p) =>
    `    { apiName: "${p.apiName}", type: "${p.baseType}", baseType: "${p.baseType}" as const, required: ${p.required}, readonly: ${p.readonly}, description: { ko: "${p.apiName}", en: "${p.apiName}" } },`
  ).join("\n");

  return `  // --- Generated by upgrade-apply.ts (${spec.sectionId}) ---
  {
    apiName: "${spec.target}",
    displayName: "${spec.target.replace(/([A-Z])/g, " $1").trim()}",
    pluralName: "${spec.target}s",
    primaryKey: "${details.primaryKey}",
    titleKey: "${details.titleKey}",
    description: { ko: "${spec.target}", en: "${spec.target} — ${spec.reason}" },
    properties: [
${propsCode}
    ],
  },`;
}

function generateMutationCode(spec: UpgradeSpec): string {
  const details = spec.details as {
    entityApiName: string;
    mutationType: string;
    parameters: Array<{ name: string; type: string; required: boolean }>;
    reviewLevel?: string;
  };

  const paramsCode = details.parameters.map((p) =>
    `      { name: "${p.name}", type: "${p.type}", required: ${p.required}, description: { ko: "${p.name}", en: "${p.name}" } },`
  ).join("\n");

  return `  // --- Generated by upgrade-apply.ts (${spec.sectionId}) ---
  {
    apiName: "${spec.target}",
    description: { ko: "${spec.target}", en: "${spec.target} — ${spec.reason}" },
    mutationType: "${details.mutationType}" as const,
    entityApiName: "${details.entityApiName}",
    parameters: [
${paramsCode}
    ],
    edits: [{ type: "${details.mutationType}" as const, target: "${details.entityApiName}" }],${details.reviewLevel ? `\n    reviewLevel: "${details.reviewLevel}" as const,` : ""}
  },`;
}

function generateConvexTable(entityName: string, properties: Array<{ apiName: string; baseType: string }>): string {
  const tableName = toCamelPlural(entityName);
  const fields = properties.map((p) => {
    const convexType = p.baseType === "string" ? "v.string()"
      : p.baseType === "integer" || p.baseType === "long" ? "v.number()"
      : p.baseType === "float" || p.baseType === "double" ? "v.float64()"
      : p.baseType === "boolean" ? "v.boolean()"
      : p.baseType === "timestamp" ? "v.number()"
      : "v.string()";
    return `    ${p.apiName}: ${convexType},`;
  }).join("\n");

  return `  // --- Generated by upgrade-apply.ts ---
  ${tableName}: defineTable({
${fields}
  }).index("by_${properties[0]?.apiName ?? "id"}", ["${properties[0]?.apiName ?? "id"}"]),`;
}

function generateConvexQuery(entityName: string): string {
  const tableName = toCamelPlural(entityName);
  const fnName = `get${entityName}s`;
  return `/** List ${entityName} records. Generated by upgrade-apply.ts. */
export const ${fnName} = query({
  args: { limit: v.optional(v.number()) },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("${tableName}")
      .order("desc")
      .take(args.limit ?? 50);
  },
});`;
}

function generateConvexMutation(spec: UpgradeSpec): string {
  const details = spec.details as {
    entityApiName: string;
    mutationType: string;
    parameters: Array<{ name: string; type: string; required: boolean }>;
  };
  const tableName = toCamelPlural(details.entityApiName);

  const args = details.parameters.map((p) => {
    const convexType = p.type === "string" ? "v.string()" : "v.number()";
    return `    ${p.name}: ${p.required ? convexType : `v.optional(${convexType})`},`;
  }).join("\n");

  const fields = details.parameters.map((p) => `      ${p.name}: args.${p.name},`).join("\n");

  return `/** ${spec.target} — ${spec.reason}. Generated by upgrade-apply.ts. */
export const ${spec.target} = mutation({
  args: {
${args}
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert("${tableName}", {
${fields}
      createdAt: Date.now(),
    });
  },
});`;
}

function generateSrcHook(entityName: string): string {
  const fnName = `get${entityName}s`;
  const hookName = `use${entityName}s`;
  return `/** Hook for ${entityName} list. Generated by upgrade-apply.ts. */
import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";

export function ${hookName}(limit = 50) {
  return useQuery(api.queries.${fnName}, { limit });
}`;
}

function generateFrontendViewCode(spec: UpgradeSpec): string {
  const details = spec.details as {
    route: string;
    surface: string;
    entityApiName?: string;
    primaryQueryRef?: string;
    mutationActionRefs?: string[];
  };

  return `  // --- Generated by upgrade-apply.ts (${spec.sectionId}) ---
  {
    apiName: "${spec.target}",
    route: "${details.route}",
    description: { ko: "${spec.target}", en: "${spec.target} — ${spec.reason}" },
    surface: "${details.surface}" as const,${details.entityApiName ? `\n    entityApiName: "${details.entityApiName}",` : ""}${details.primaryQueryRef ? `\n    primaryQueryRef: "${details.primaryQueryRef}",` : ""}
    secondaryQueryRefs: [],
    mutationActionRefs: ${JSON.stringify(details.mutationActionRefs ?? [])},
  },`;
}

function generateFrontendAgentSurfaceCode(spec: UpgradeSpec): string {
  const details = spec.details as {
    surface: string;
    entityApiName?: string;
    queryRefs?: string[];
    functionRefs?: string[];
    actionRefs?: string[];
    reviewLevel?: string;
  };

  return `  // --- Generated by upgrade-apply.ts (${spec.sectionId}) ---
  {
    apiName: "${spec.target}",
    description: { ko: "${spec.target}", en: "${spec.target} — ${spec.reason}" },
    surface: "${details.surface}" as const,${details.entityApiName ? `\n    entityApiName: "${details.entityApiName}",` : ""}
    queryRefs: ${JSON.stringify(details.queryRefs ?? [])},
    functionRefs: ${JSON.stringify(details.functionRefs ?? [])},
    actionRefs: ${JSON.stringify(details.actionRefs ?? [])},${details.reviewLevel ? `\n    reviewLevel: "${details.reviewLevel}" as const,` : ""}
  },`;
}

function generateScenarioFlowCode(spec: UpgradeSpec): string {
  const details = spec.details as {
    scenarioEntityApiName: string;
    comparisonFunctionRefs?: string[];
    submitActionRef: string;
    commitActionRef?: string;
  };

  return `  // --- Generated by upgrade-apply.ts (${spec.sectionId}) ---
  {
    apiName: "${spec.target}",
    description: { ko: "${spec.target}", en: "${spec.target} — ${spec.reason}" },
    scenarioEntityApiName: "${details.scenarioEntityApiName}",
    comparisonFunctionRefs: ${JSON.stringify(details.comparisonFunctionRefs ?? [])},
    submitActionRef: "${details.submitActionRef}",${details.commitActionRef ? `\n    commitActionRef: "${details.commitActionRef}",` : ""}
  },`;
}

// =========================================================================
// Main Generator
// =========================================================================

/**
 * Generate code patches from UpgradeSpecs.
 *
 * @param specs - UpgradeSpec[] from auditSemantics().upgradeSpecs
 * @param projectName - project directory name (e.g., "saveticker")
 * @returns UpgradeResult with file patches for all 3 layers
 */
export function generateUpgrades(specs: readonly UpgradeSpec[], projectName: string): UpgradeResult {
  const patches: FilePatch[] = [];
  const convexTables: string[] = [];
  let applied = 0;
  let skipped = 0;

  for (const spec of specs) {
    switch (spec.operation) {
      case "addEntity": {
        const details = spec.details as {
          properties: Array<{ apiName: string; baseType: string; required: boolean; readonly: boolean }>;
          primaryKey: string;
          titleKey: string;
        };

        // Layer 1: ontology/data.ts
        patches.push({
          filePath: `${projectName}/ontology/data.ts`,
          layer: "ontology",
          operation: "append",
          content: generateEntityCode(spec),
          description: `Add ${spec.target} entity (${spec.sectionId}: ${spec.reason})`,
        });

        // Layer 2: convex/schema.ts
        const tableName = toCamelPlural(spec.target);
        convexTables.push(tableName);
        patches.push({
          filePath: `${projectName}/convex/schema.ts`,
          layer: "convex",
          operation: "append",
          content: generateConvexTable(spec.target, details.properties),
          description: `Add ${tableName} table`,
        });

        // Layer 2: convex/queries.ts
        patches.push({
          filePath: `${projectName}/convex/queries.ts`,
          layer: "convex",
          operation: "append",
          content: generateConvexQuery(spec.target),
          description: `Add get${spec.target}s query`,
        });

        // Layer 3: src/hooks/
        patches.push({
          filePath: `${projectName}/src/hooks/use${spec.target}s.ts`,
          layer: "src",
          operation: "create",
          content: generateSrcHook(spec.target),
          description: `Add use${spec.target}s hook`,
        });

        applied++;
        break;
      }

      case "addMutation": {
        // Layer 1: ontology/action.ts
        patches.push({
          filePath: `${projectName}/ontology/action.ts`,
          layer: "ontology",
          operation: "append",
          content: generateMutationCode(spec),
          description: `Add ${spec.target} mutation (${spec.sectionId}: ${spec.reason})`,
        });

        // Layer 2: convex/mutations.ts
        patches.push({
          filePath: `${projectName}/convex/mutations.ts`,
          layer: "convex",
          operation: "append",
          content: generateConvexMutation(spec),
          description: `Add ${spec.target} convex mutation`,
        });

        applied++;
        break;
      }

      case "modifyFunction": {
        const details = spec.details as { field: string; value: unknown };
        patches.push({
          filePath: `${projectName}/ontology/logic.ts`,
          layer: "ontology",
          operation: "insert",
          content: `// upgrade-apply: set ${details.field}=${JSON.stringify(details.value)} on ${spec.target} (${spec.sectionId})`,
          description: `Modify ${spec.target}: set ${details.field}=${JSON.stringify(details.value)}`,
        });
        applied++;
        break;
      }

      case "addProperty": {
        const details = spec.details as {
          properties: Array<{ apiName: string; baseType: string }>;
        };
        patches.push({
          filePath: `${projectName}/ontology/data.ts`,
          layer: "ontology",
          operation: "insert",
          content: details.properties.map((p) =>
            `    // upgrade-apply (${spec.sectionId}): add { apiName: "${p.apiName}", baseType: "${p.baseType}" } to ${spec.target}`
          ).join("\n"),
          description: `Add ${details.properties.length} properties to ${spec.target} (${spec.sectionId})`,
        });
        applied++;
        break;
      }

      case "addLink": {
        const details = spec.details as {
          sourceEntity: string;
          targetEntity: string;
          cardinality: string;
        };
        // Layer 1: ontology/logic.ts
        patches.push({
          filePath: `${projectName}/ontology/logic.ts`,
          layer: "ontology",
          operation: "append",
          content: `  // --- Generated by upgrade-apply.ts (${spec.sectionId}) ---
  {
    apiName: "${spec.target}",
    description: { ko: "${spec.target}", en: "${spec.target} — ${spec.reason}" },
    sourceEntity: "${details.sourceEntity}",
    targetEntity: "${details.targetEntity}",
    cardinality: "${details.cardinality}" as const,
  },`,
          description: `Add ${spec.target} link (${spec.sectionId}: ${spec.reason})`,
        });
        // Layer 2/3: Link types do not generate convex/src stubs (they map to FK/join patterns)
        applied++;
        break;
      }

      case "addQuery": {
        const details = spec.details as {
          entityApiName: string;
          queryType: string;
        };
        // Layer 1: ontology/logic.ts
        patches.push({
          filePath: `${projectName}/ontology/logic.ts`,
          layer: "ontology",
          operation: "append",
          content: `  // --- Generated by upgrade-apply.ts (${spec.sectionId}) ---
  {
    apiName: "${spec.target}",
    description: { ko: "${spec.target}", en: "${spec.target} — ${spec.reason}" },
    entityApiName: "${details.entityApiName}",
    queryType: "${details.queryType}" as const,
  },`,
          description: `Add ${spec.target} query (${spec.sectionId}: ${spec.reason})`,
        });
        // Layer 2: convex/queries.ts
        patches.push({
          filePath: `${projectName}/convex/queries.ts`,
          layer: "convex",
          operation: "append",
          content: generateConvexQuery(details.entityApiName),
          description: `Add ${spec.target} convex query`,
        });
        applied++;
        break;
      }

      case "addWebhook": {
        // Layer 1: ontology/action.ts
        patches.push({
          filePath: `${projectName}/ontology/action.ts`,
          layer: "ontology",
          operation: "append",
          content: `  // --- Generated by upgrade-apply.ts (${spec.sectionId}) ---
  // Webhook: ${spec.target} — ${spec.reason}
  // Implementation: configure webhook endpoint in convex/http.ts`,
          description: `Add ${spec.target} webhook declaration (${spec.sectionId}: ${spec.reason})`,
        });
        // Layer 2/3: Webhooks map to HTTP routes — warn about manual implementation
        console.warn(`[upgrade-apply] addWebhook "${spec.target}": Layer 1 patch generated. Layer 2 (convex/http.ts) and Layer 3 require manual implementation.`);
        applied++;
        break;
      }

      default:
        console.warn(`[upgrade-apply] Unknown operation "${spec.operation}" for spec "${spec.target}" — skipped.`);
        skipped++;
    }
  }

  // Group patches by layer for summary
  const ontologyPatches = patches.filter((p) => p.layer === "ontology").length;
  const convexPatches = patches.filter((p) => p.layer === "convex").length;
  const srcPatches = patches.filter((p) => p.layer === "src").length;

  return {
    totalSpecs: specs.length,
    appliedSpecs: applied,
    skippedSpecs: skipped,
    patches,
    convexTableNames: convexTables,
    summary: `Generated ${patches.length} patches (ontology: ${ontologyPatches}, convex: ${convexPatches}, src: ${srcPatches}) from ${applied} specs`,
  };
}

/**
 * Preferred entry point — name clarifies this is scaffold generation, not semantic transformation.
 * @see generateUpgrades for backward-compatible alias
 */
export const generateUpgradeScaffolds = generateUpgrades;

/**
 * Print upgrade patches as a human-readable report.
 */
export function printUpgradeReport(result: UpgradeResult): void {
  console.log(`\n  Upgrade Report: ${result.summary}`);
  console.log(`  Specs: ${result.appliedSpecs} applied, ${result.skippedSpecs} skipped`);
  if (result.convexTableNames.length > 0) {
    console.log(`  New Convex tables: ${result.convexTableNames.join(", ")}`);
  }
  console.log("");

  for (const patch of result.patches) {
    const icon = patch.layer === "ontology" ? "[ONT]" : patch.layer === "convex" ? "[CVX]" : "[SRC]";
    console.log(`  ${icon} ${patch.operation.toUpperCase()} ${patch.filePath}`);
    console.log(`       ${patch.description}`);
  }
}
