/**
 * OSDK 2.0 template utilities
 * @owner palantirkc-plugin-codegen
 * @purpose OSDK 2.0 template utilities
 */
// palantir-mini v0 — OSDK 2.0 template utilities
// Domain: DATA (prim-data-02 ObjectType) + LOGIC (generator primitives)
//
// Produces OSDK 2.0-compliant TypeScript templates for ObjectType, LinkType,
// ActionType, and InterfaceType declarations. Uses:
//   - Branded RID types (nominal safety at zero runtime cost)
//   - Exhaustive visitor unions on discriminated types
//   - Namespace-merge-free architecture (separated client/generated split)
//
// Templates are string builders. descender-gen.ts composes these into full files.

export interface PrimitiveMetadata {
  name: string;
  kind: "ObjectType" | "LinkType" | "ActionType" | "InterfaceType" | "PropertyType";
  description?: string;
  properties?: Array<{ name: string; type: string; optional?: boolean }>;
  links?: Array<{ name: string; to: string; cardinality: "one" | "many" }>;
}

const HEADER = `// AUTO-GENERATED by palantir-mini descender-gen.ts — DO NOT EDIT.
// Source: ~/.claude/schemas/ontology/
// Regenerate via: /palantir-mini:codegen or bun run lib/codegen/descender-gen.ts <project>
`;

/** Branded RID declaration: \`type XRid = string & { __brand: "XRid" };\` */
export function brandedRid(name: string): string {
  return `export type ${name}Rid = string & { readonly __brand: "${name}Rid" };`;
}

/** Smart constructor for a branded type */
export function brandedCtor(name: string): string {
  return `export const ${name[0]!.toLowerCase()}${name.slice(1)}Rid = (s: string): ${name}Rid => s as ${name}Rid;`;
}

/** ObjectType template */
export function generateObjectType(meta: PrimitiveMetadata): string {
  const props = (meta.properties ?? [])
    .map((p) => `  ${p.name}${p.optional ? "?" : ""}: ${p.type};`)
    .join("\n");

  return [
    `// ObjectType: ${meta.name}`,
    meta.description ? `// ${meta.description}` : "",
    brandedRid(meta.name),
    brandedCtor(meta.name),
    "",
    `export interface ${meta.name} {`,
    `  readonly rid: ${meta.name}Rid;`,
    props || "  // no properties declared",
    `}`,
  ].filter((l) => l !== "").join("\n");
}

/** LinkType template */
export function generateLinkType(meta: PrimitiveMetadata): string {
  return [
    `// LinkType: ${meta.name}`,
    meta.description ? `// ${meta.description}` : "",
    brandedRid(meta.name),
    "",
    `export interface ${meta.name}Link {`,
    `  readonly rid: ${meta.name}Rid;`,
    `  readonly srcRid: string;`,
    `  readonly dstRid: string;`,
    `  readonly linkName: "${meta.name}";`,
    `}`,
  ].filter((l) => l !== "").join("\n");
}

/** ActionType template */
export function generateActionType(meta: PrimitiveMetadata): string {
  return [
    `// ActionType: ${meta.name}`,
    meta.description ? `// ${meta.description}` : "",
    brandedRid(meta.name),
    "",
    `export interface ${meta.name}Action {`,
    `  readonly rid: ${meta.name}Rid;`,
    `  readonly tier: "tier-1" | "tier-2";`,
    `}`,
  ].filter((l) => l !== "").join("\n");
}

/** File-level wrapper with header + exports */
export function wrapGeneratedFile(sections: string[]): string {
  return HEADER + "\n" + sections.join("\n\n") + "\n";
}

export { HEADER };
