/**
 * palantir-mini SELF-ONTOLOGY barrel (M-SELF home).
 *
 * pm's OWN control surface registered as typed Palantir primitive instances —
 * the deliverable that un-latents the self-Ontology (register-grep was 0 across
 * the snapshot; see `pm-self-ontology-milestone`). Importing this barrel executes
 * each instance module, which self-registers into the primitive registries.
 *
 * M-SELF counter (effort README §M-SELF): instances accrue one per neutralized
 * wave (W3d/e/f). Today: 2 ObjectType (SemanticIntentContract, McpTool) + 1
 * ActionType (Executor) + 1 embedded Struct (SicAxis). W3e-3a added the Executor
 * ActionType + the McpTool ObjectType (29 tool instances). W3f wires `self/links.ts`
 * (LinkTypes) and runs the dogfood (ONTOLOGY_DTC_BUILD_SEQUENCE ready-for-dtc +
 * propagation_audit_forward with pm as subject).
 *
 * @owner palantirkc-ontology
 */

export {
  SIC_AXIS_STRUCT,
  SIC_AXIS_STRUCT_RID,
} from "./sic-axis.struct";
export {
  SEMANTIC_INTENT_CONTRACT_OBJECT_TYPE,
  SEMANTIC_INTENT_CONTRACT_OBJECT_TYPE_RID,
} from "./semantic-intent-contract.objecttype";
export {
  EXECUTOR_ACTION_TYPE,
  EXECUTOR_ACTION_TYPE_RID,
} from "./executor.actiontype";
export {
  REGISTER_OBJECT_TYPE_ACTION_TYPE,
  REGISTER_OBJECT_TYPE_ACTION_TYPE_RID,
  REGISTER_LINK_TYPE_ACTION_TYPE,
  REGISTER_LINK_TYPE_ACTION_TYPE_RID,
  REGISTER_ACTION_TYPE_ACTION_TYPE,
  REGISTER_ACTION_TYPE_ACTION_TYPE_RID,
  REGISTER_FUNCTION_ACTION_TYPE,
  REGISTER_FUNCTION_ACTION_TYPE_RID,
  REGISTER_TIER1_DECLARATIVE_ACTION_ACTION_TYPE,
  REGISTER_TIER1_DECLARATIVE_ACTION_ACTION_TYPE_RID,
  COMMIT_EDITS_ACTION_TYPE,
  COMMIT_EDITS_ACTION_TYPE_RID,
  APPLY_EDIT_FUNCTION_ACTION_TYPE,
  APPLY_EDIT_FUNCTION_ACTION_TYPE_RID,
  EMIT_EVENT_ACTION_TYPE,
  EMIT_EVENT_ACTION_TYPE_RID,
  ROTATE_EVENTS_ACTION_TYPE,
  ROTATE_EVENTS_ACTION_TYPE_RID,
  PROMOTE_VALUE_GRADE_ACTION_TYPE,
  PROMOTE_VALUE_GRADE_ACTION_TYPE_RID,
  DRAFT_SEMANTIC_INTENT_CONTRACT_ACTION_TYPE,
  DRAFT_SEMANTIC_INTENT_CONTRACT_ACTION_TYPE_RID,
  APPROVE_DIGITAL_TWIN_CHANGE_CONTRACT_ACTION_TYPE,
  APPROVE_DIGITAL_TWIN_CHANGE_CONTRACT_ACTION_TYPE_RID,
  ADVANCE_ONTOLOGY_ENGINEERING_WORKFLOW_ACTION_TYPE,
  ADVANCE_ONTOLOGY_ENGINEERING_WORKFLOW_ACTION_TYPE_RID,
  ADVANCE_FDE_ONTOLOGY_BUILD_TURN_ACTION_TYPE,
  ADVANCE_FDE_ONTOLOGY_BUILD_TURN_ACTION_TYPE_RID,
  RECORD_PRE_MUTATION_GOVERNANCE_DECISION_ACTION_TYPE,
  RECORD_PRE_MUTATION_GOVERNANCE_DECISION_ACTION_TYPE_RID,
  ROUTE_INTENT_DISPATCH_ACTION_TYPE,
  ROUTE_INTENT_DISPATCH_ACTION_TYPE_RID,
  MINT_PROMPT_ENVELOPE_ACTION_TYPE,
  MINT_PROMPT_ENVELOPE_ACTION_TYPE_RID,
  PROMOTE_EVIDENCE_ACTION_TYPE,
  PROMOTE_EVIDENCE_ACTION_TYPE_RID,
  REGISTER_CAPABILITY_TOKEN_ACTION_TYPE,
  REGISTER_CAPABILITY_TOKEN_ACTION_TYPE_RID,
  EVALUATE_RELEASE_GATE_ACTION_TYPE,
  EVALUATE_RELEASE_GATE_ACTION_TYPE_RID,
  STRUCTURED_OUTPUT_ACTION_TYPE,
  STRUCTURED_OUTPUT_ACTION_TYPE_RID,
  SELF_ACTION_TYPES,
} from "./action-types";
export {
  FUNCTION_OBJECT_TYPE,
  FUNCTION_OBJECT_TYPE_RID,
  FUNCTION_INSTANCES,
  type FunctionInstance,
} from "./functions";
export {
  MCP_TOOL_OBJECT_TYPE,
  MCP_TOOL_OBJECT_TYPE_RID,
  MCP_TOOL_INSTANCES,
  type McpToolInstance,
} from "./mcp-tool.objecttype";
export {
  SKILL_OBJECT_TYPE,
  SKILL_OBJECT_TYPE_RID,
  SKILL_INSTANCES,
  type SkillInstance,
} from "./skill.objecttype";
export {
  AGENT_OBJECT_TYPE,
  AGENT_OBJECT_TYPE_RID,
  AGENT_INSTANCES,
  type AgentInstance,
} from "./agent.objecttype";
export {
  HOOK_OBJECT_TYPE,
  HOOK_OBJECT_TYPE_RID,
  HOOK_INSTANCES,
  type HookInstance,
} from "./hook.objecttype";
export {
  MCP_HANDLER_OBJECT_TYPE,
  MCP_HANDLER_OBJECT_TYPE_RID,
  MCP_HANDLER_INSTANCES,
  type McpHandlerInstance,
} from "./mcp-handler.objecttype";
export {
  EVENT_ENVELOPE_OBJECT_TYPE,
  EVENT_ENVELOPE_OBJECT_TYPE_RID,
  EVENT_ENVELOPE_INSTANCES,
  type EventEnvelopeInstance,
} from "./event-envelope.objecttype";
export {
  CAPABILITY_CONTRACT_OBJECT_TYPE,
  CAPABILITY_CONTRACT_OBJECT_TYPE_RID,
  CAPABILITY_CONTRACT_INSTANCES,
  type CapabilityContractInstance,
} from "./capability-contract.objecttype";
export {
  CAPABILITY_TOKEN_OBJECT_TYPE,
  CAPABILITY_TOKEN_OBJECT_TYPE_RID,
  CAPABILITY_TOKEN_INSTANCES,
  type CapabilityTokenInstance,
} from "./capability-token.objecttype";
export {
  CONTEXT_CAPSULE_OBJECT_TYPE,
  CONTEXT_CAPSULE_OBJECT_TYPE_RID,
  CONTEXT_CAPSULE_INSTANCES,
  type ContextCapsuleInstance,
} from "./context-capsule.objecttype";
export {
  DIGITAL_TWIN_CHANGE_CONTRACT_OBJECT_TYPE,
  DIGITAL_TWIN_CHANGE_CONTRACT_OBJECT_TYPE_RID,
  DIGITAL_TWIN_CHANGE_CONTRACT_INSTANCES,
  type DigitalTwinChangeContractInstance,
} from "./digital-twin-change-contract.objecttype";
export {
  EDIT_FUNCTION_OBJECT_TYPE,
  EDIT_FUNCTION_OBJECT_TYPE_RID,
  EDIT_FUNCTION_INSTANCES,
  type EditFunctionInstance,
} from "./edit-function.objecttype";
export {
  EVAL_SUITE_OBJECT_TYPE,
  EVAL_SUITE_OBJECT_TYPE_RID,
  EVAL_SUITE_INSTANCES,
  type EvalSuiteInstance,
} from "./eval-suite.objecttype";
export {
  FDE_ONTOLOGY_BUILD_SESSION_OBJECT_TYPE,
  FDE_ONTOLOGY_BUILD_SESSION_OBJECT_TYPE_RID,
  FDE_ONTOLOGY_BUILD_SESSION_INSTANCES,
  type FdeOntologyBuildSessionInstance,
} from "./fde-ontology-build-session.objecttype";
export {
  GRADING_RUBRIC_OBJECT_TYPE,
  GRADING_RUBRIC_OBJECT_TYPE_RID,
  GRADING_RUBRIC_INSTANCES,
  type GradingRubricInstance,
} from "./grading-rubric.objecttype";
export {
  IMPACT_EDGE_OBJECT_TYPE,
  IMPACT_EDGE_OBJECT_TYPE_RID,
  IMPACT_EDGE_INSTANCES,
  type ImpactEdgeInstance,
} from "./impact-edge.objecttype";
export {
  LEARNING_OBJECT_TYPE,
  LEARNING_OBJECT_TYPE_RID,
  LEARNING_INSTANCES,
  type LearningInstance,
} from "./learning.objecttype";
export {
  MANAGED_SETTINGS_FRAGMENT_OBJECT_TYPE,
  MANAGED_SETTINGS_FRAGMENT_OBJECT_TYPE_RID,
  MANAGED_SETTINGS_FRAGMENT_INSTANCES,
  type ManagedSettingsFragmentInstance,
} from "./managed-settings-fragment.objecttype";
export {
  MONITOR_OBJECT_TYPE,
  MONITOR_OBJECT_TYPE_RID,
  MONITOR_INSTANCES,
  type MonitorInstance,
} from "./monitor.objecttype";
export {
  PLUGIN_MANIFEST_OBJECT_TYPE,
  PLUGIN_MANIFEST_OBJECT_TYPE_RID,
  PLUGIN_MANIFEST_INSTANCES,
  type PluginManifestInstance,
} from "./plugin-manifest.objecttype";
export {
  PROJECT_ONTOLOGY_INDEX_OBJECT_TYPE,
  PROJECT_ONTOLOGY_INDEX_OBJECT_TYPE_RID,
  PROJECT_ONTOLOGY_INDEX_INSTANCES,
  type ProjectOntologyIndexInstance,
} from "./project-ontology-index.objecttype";
export {
  PROMPT_ENVELOPE_OBJECT_TYPE,
  PROMPT_ENVELOPE_OBJECT_TYPE_RID,
  PROMPT_ENVELOPE_INSTANCES,
  type PromptEnvelopeInstance,
} from "./prompt-envelope.objecttype";
export {
  RULE_OBJECT_TYPE,
  RULE_OBJECT_TYPE_RID,
  RULE_INSTANCES,
  type RuleInstance,
} from "./rule.objecttype";
export {
  RUNTIME_ADAPTER_OBJECT_TYPE,
  RUNTIME_ADAPTER_OBJECT_TYPE_RID,
  RUNTIME_ADAPTER_INSTANCES,
  type RuntimeAdapterInstance,
} from "./runtime-adapter.objecttype";
export {
  RUNTIME_DECISION_OBJECT_TYPE,
  RUNTIME_DECISION_OBJECT_TYPE_RID,
  RUNTIME_DECISION_INSTANCES,
  type RuntimeDecisionInstance,
} from "./runtime-decision.objecttype";
export {
  SCENARIO_SANDBOX_OBJECT_TYPE,
  SCENARIO_SANDBOX_OBJECT_TYPE_RID,
  SCENARIO_SANDBOX_INSTANCES,
  type ScenarioSandboxInstance,
} from "./scenario-sandbox.objecttype";
export {
  SUBMISSION_CRITERION_OBJECT_TYPE,
  SUBMISSION_CRITERION_OBJECT_TYPE_RID,
  SUBMISSION_CRITERION_INSTANCES,
  type SubmissionCriterionInstance,
} from "./submission-criterion.objecttype";
export {
  UNIVERSAL_ONTOLOGY_ENTRY_OBJECT_TYPE,
  UNIVERSAL_ONTOLOGY_ENTRY_OBJECT_TYPE_RID,
  UNIVERSAL_ONTOLOGY_ENTRY_INSTANCES,
  type UniversalOntologyEntryInstance,
} from "./universal-ontology-entry.objecttype";
export {
  WORKFLOW_TRACE_OBJECT_TYPE,
  WORKFLOW_TRACE_OBJECT_TYPE_RID,
  WORKFLOW_TRACE_INSTANCES,
  type WorkflowTraceInstance,
} from "./workflow-trace.objecttype";

// Self-Ontology Role instances (principal->permission grants). Re-exporting
// these decls also runs roles.ts as a side-effect import, self-registering all
// 7 Roles (5 agent file-ownership + 2 capability-split) into ROLE_REGISTRY.
export {
  HOOK_BUILDER_ROLE,
  HOOK_BUILDER_ROLE_RID,
  PLUGIN_MAINTAINER_ROLE,
  PLUGIN_MAINTAINER_ROLE_RID,
  PROTOCOL_DESIGNER_ROLE,
  PROTOCOL_DESIGNER_ROLE_RID,
  TASK_OWNER_ROLE,
  TASK_OWNER_ROLE_RID,
  SHARED_LIB_ROLE,
  SHARED_LIB_ROLE_RID,
  READ_ONLY_CAPABILITY_ROLE,
  READ_ONLY_CAPABILITY_ROLE_RID,
  MUTATING_CAPABILITY_ROLE,
  MUTATING_CAPABILITY_ROLE_RID,
  READ_ONLY_AGENT_IDS,
  MUTATING_AGENT_IDS,
  ROLE_DECLARATIONS,
  ROLE_INSTANCES,
  type RoleInstance,
} from "./roles";

// Self-Ontology LinkTypes (W3f). Re-exporting these decls also runs links.ts as a
// side-effect import, self-registering all 33 LinkTypes into LINK_TYPE_REGISTRY.
export {
  MCP_TOOL_BACKED_BY_MCP_HANDLER,
  SKILL_INVOKES_MCP_TOOL,
  AGENT_USES_SKILL,
  HOOK_ENFORCES_RULE,
  RULE_CROSS_REFS_RULE,
  SEMANTIC_INTENT_CONTRACT_DERIVES_DIGITAL_TWIN_CHANGE_CONTRACT,
  SEMANTIC_INTENT_CONTRACT_SUPERSEDES_PRIOR_CONTRACT,
  DIGITAL_TWIN_CHANGE_CONTRACT_TOUCHES_PROJECT_ONTOLOGY_INDEX,
  RUNTIME_DECISION_GATED_BY_DIGITAL_TWIN_CHANGE_CONTRACT,
  RUNTIME_DECISION_EMITS_EVENT_ENVELOPE,
  EVENT_ENVELOPE_BELONGS_TO_WORKFLOW_TRACE,
  WORKFLOW_TRACE_REFINES_PRIOR_TRACE,
  LEARNING_REFINES_RUNTIME_DECISION,
  EVAL_SUITE_SCORED_BY_GRADING_RUBRIC,
  EVAL_SUITE_EVALUATES_AGENT,
  CAPABILITY_CONTRACT_UNIFIES_SKILL,
  CAPABILITY_CONTRACT_UNIFIES_AGENT,
  CAPABILITY_CONTRACT_UNIFIES_MCP_TOOL,
  PLUGIN_MANIFEST_REGISTERS_MCP_TOOL,
  PLUGIN_MANIFEST_REGISTERS_HOOK,
  PLUGIN_MANIFEST_REGISTERS_SKILL,
  PLUGIN_MANIFEST_REGISTERS_AGENT,
  MANAGED_SETTINGS_FRAGMENT_GRANTS_MCP_TOOL,
  MANAGED_SETTINGS_FRAGMENT_SCOPED_TO_PLUGIN_MANIFEST,
  HOOK_GUARDS_ACTION_VIA_SUBMISSION_CRITERION,
  EDIT_FUNCTION_PROPOSES_DIGITAL_TWIN_CHANGE_CONTRACT,
  SANDBOX_SESSION_EXECUTES_EDIT_FUNCTION,
  SANDBOX_SESSION_RESUMES_PRIOR_SESSION,
  AGENT_OWNS_CAPABILITY_CONTRACT,
  GRADING_RUBRIC_GRADES_SEMANTIC_INTENT_CONTRACT,
  RUNTIME_DECISION_PROJECTED_FROM_NEUTRAL_DECISION,
  RUNTIME_ADAPTER_PROJECTS_RUNTIME_DECISION,
  PROMPT_ENVELOPE_DERIVES_SEMANTIC_INTENT_CONTRACT,
} from "./links";

// Self-Ontology derived view (DoD #4): the DATA/LOGIC/ACTION/GOVERNANCE 4-axis projection
// GENERATED from the registries above — not a hand-authored list. See derived-view.ts header.
export {
  generateDerivedView,
  type DerivedView,
  type DerivedViewAxis,
  type DerivedViewEntry,
} from "./derived-view";
