import type { ProjectScopeDefinition } from "./types";

export const educationProjectScope: ProjectScopeDefinition = {
  projectId: "education-template",
  sourcePath: "lib/project-scope/education-defaults.ts",
  writableRoot: ".",
  forbiddenPatterns: ["src/generated/**"],
  domainAgents: ["implementer", "project-implementer"],
  pathMarkers: ["projects/palantir-math/", "palantir-math/"],
  projectOntologyAxes: [
    {
      id: "learning-domain",
      owns: ["curriculum taxonomy", "problem kind", "formula/domain labels", "teaching intent"],
      currentAuthority: ["docs/curriculum", "ontology/data/sequencer.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/curriculumTaxonomy.ts", "src/lib/semanticPlan.ts"],
      migrationTarget: "Keep reusable math meaning independent from any one renderer or surface.",
      bottleneck: "SeqData currently carries domain, lesson, rendering, and workflow meaning in one root artifact.",
      laneRefs: ["seq.problem-content", "seq.step-formula-logic", "seq.semantic-plan"],
    },
    {
      id: "lesson-artifact",
      owns: ["SeqData", "SeqFrames", "SemanticPlan", "frameOverrides", "global/banded overrides"],
      currentAuthority: ["ontology/data/sequencer.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/seqDataAuthority.ts", "src/lib/problemHydration.ts", "src/lib/localDraftSave.ts"],
      migrationTarget: "Declare SeqData as a composed lesson artifact with separately named semantic lanes.",
      bottleneck: "Frame-local, banded, global, semantic-plan, and scene data need one compositional ontology axis.",
      laneRefs: [
        "seq.identity",
        "seq.problem-content",
        "seq.step-formula-logic",
        "seq.teaching-narrative",
        "seq.frame-overrides",
        "seq.scope-cascade",
        "seq.workbench-authoring",
      ],
    },
    {
      id: "surface-authority",
      owns: ["surface ownership", "route/view boundaries", "mutation scope"],
      currentAuthority: ["ontology/frontend.ts", "ontology/runtime.ts", "INDEX.md"],
      descenders: ["src/App.tsx", "src/lib/frontendScope.ts", "src/lib/runtimeScope.ts"],
      migrationTarget: "Make route/view boundaries queryable before edits.",
      bottleneck: "Surface invariants can be bypassed when whole-ontology work lacks a single lookup.",
    },
    {
      id: "interaction-semantics",
      owns: ["gestures", "drag roles", "student exploration", "live delegation"],
      currentAuthority: ["interaction/schema.ts", "ontology/runtime.ts", "ontology/capabilities.ts"],
      descenders: ["src/lib/jsxGraph", "src/lib/playbook", "src/lib/motion"],
      migrationTarget: "Treat gesture intent as semantic and renderer-neutral.",
      bottleneck: "Renderer implementation details can look like interaction meaning unless a contract separates them.",
      laneRefs: ["seq.rendering-scene"],
    },
    {
      id: "rendering-semantics",
      owns: ["SceneV4", "JSXGraphScene", "canvas mode", "visual components", "future Scene3D"],
      currentAuthority: ["ontology/data/visual.ts", "rendering/schema.ts", "ontology/capabilities/scene.ts"],
      descenders: ["src/lib/jsxGraphRenderer.ts", "src/lib/jsxGraph/sceneCompiler.ts"],
      migrationTarget: "Keep 3D additive and deferred; do not widen 2D SceneV4 without an approved contract.",
      bottleneck: "2D renderer terms, future 3D terms, and visual editor language can collide in raw prompts.",
      laneRefs: ["seq.rendering-scene", "seq.flow-scene"],
    },
    {
      id: "effect-semantics",
      owns: ["effectInline", "Design HOW-only authoring", "animation/effect presets"],
      currentAuthority: ["ontology/capabilities/sequencer.ts", "ontology/frontend.ts", "src/types/seq-data.ts"],
      descenders: ["src/components/design", "src/components/ui/InlineEffectPopover.tsx"],
      migrationTarget: "Preserve HOW-only Design edits as frame/target effect configuration, not structure.",
      bottleneck: "Effect ownership historically moved between Studio and Sequencer-era surfaces.",
      laneRefs: ["seq.effect-authoring"],
    },
    {
      id: "persistence-publication",
      owns: ["local draft", "artifact snapshots", "Cloud publish", "source precedence"],
      currentAuthority: ["ontology/runtime.ts", "BROWSE.md", "INDEX.md"],
      descenders: ["src/lib/localArtifactBridge.ts", "src/lib/cloudRuntimeSync.ts", "scripts/publish-to-cloud.ts"],
      migrationTarget: "Keep Save Draft local-first and Publish as the only explicit Cloud boundary.",
      bottleneck: "Semantic repair can accidentally become persistence behavior change.",
    },
    {
      id: "agent-routing",
      owns: ["change contracts", "capability contracts", "runtime-native docs", "SemanticIntentContract"],
      currentAuthority: ["ontology/changeContracts.ts", "ontology/capabilities.ts", "AGENTS.md", "CLAUDE.md"],
      descenders: ["src/generated/change-registry.generated.ts", "src/generated/capability-registry.generated.ts"],
      migrationTarget: "Require SemanticIntentContract and DigitalTwinChangeContract before broad ontology migrations.",
      bottleneck: "Narrow resolvers do not fully cover project-scope redesign intent.",
    },
    {
      id: "evaluation-lineage",
      owns: ["validation packs", "semantic loop", "runtime QA", "audit/learn BackPropagation"],
      currentAuthority: ["ontology/changeContracts/meta.ts", "ontology/data/learn.ts", "ontology/action.ts"],
      descenders: ["tests", "src/tools/runSemanticLoop.ts", "scripts/qa"],
      migrationTarget: "Make every migration replayable through deterministic checks and lineage.",
      bottleneck: "QA ladders exist, but the selected ladder is not always contract-derived.",
      laneRefs: ["seq.lineage-feedback", "seq.semantic-plan"],
    },
  ],
  surfaceMutationBoundaries: [
    {
      surface: "ProblemLibrary",
      owns: ["browse", "triage", "launch affordances"],
      mustNotOwn: ["authoring semantics", "implicit cloud writes"],
      durableWriteBoundary: "view state and route selection only",
    },
    {
      surface: "Sequencer",
      owns: ["structure", "formulas", "conditions", "frame order", "scene authoring", "local drafts"],
      mustNotOwn: ["implicit cloud publish", "Presenter-only playback state"],
      durableWriteBoundary: "SeqData, SeqFrames, and frame override authoring",
    },
    {
      surface: "Design",
      owns: ["HOW-only effect authoring", "effectInline target configuration"],
      mustNotOwn: ["structural edits", "hidden Presenter writes"],
      durableWriteBoundary: "seqData.frameOverrides.effectInline",
    },
    {
      surface: "Presenter",
      owns: ["playback", "ephemeral drag", "live lecture interaction", "audit signals"],
      mustNotOwn: ["authoring mutations", "structural edits"],
      durableWriteBoundary: "runtime-local state plus explicit live-session actions",
    },
    {
      surface: "PlayBook",
      owns: ["published playback package", "standalone Presenter parity"],
      mustNotOwn: ["new authoring semantics"],
      durableWriteBoundary: "compiled/published playback artifact",
    },
    {
      surface: "Publish",
      owns: ["explicit Cloud boundary"],
      mustNotOwn: ["background persistence", "local draft autosave"],
      durableWriteBoundary: "operator-triggered cloud sync only",
    },
  ],
  seqDataLaneInventory: [
    {
      id: "context-engineering-entry",
      axis: "agent-routing",
      fields: [
        "SemanticIntentContract",
        "DigitalTwinChangeContract",
        "nonGoals",
        "downstreamForbidden",
      ],
      writerSurfaces: ["Lead", "pm_semantic_intent_gate"],
      readerSurfaces: ["pm_intent_router", "SprintContract", "harness", "project-implementer"],
      durableBoundary:
        "AIP #3 user-Lead intent bridge and AIP #4 ontology activation boundary; no Layer 1+ work routes from raw prompt text alone",
      currentAuthority: [
        "lib/context-engineering/intent-bridge.ts",
        "lib/context-engineering/ontology-activation.ts",
        "lib/lead-intent/contracts.ts",
      ],
      descenders: [
        "bridge/handlers/pm-semantic-intent-gate.ts",
        "bridge/handlers/pm-intent-router.ts",
      ],
      validationPacks: ["context-engineering-readiness", "prompt-dtc-continuity"],
      changeContractId: "change.layer0.contextEngineeringEntry",
    },
    {
      id: "seq.identity",
      axis: "lesson-artifact",
      fields: ["version", "problemId", "contentKind", "theme"],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["ProblemLibrary", "Sequencer", "Design", "Presenter", "PlayBook"],
      durableBoundary: "artifact identity and display baseline; no runtime route or publish side effect",
      currentAuthority: ["ontology/data/sequencer.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/loadProblemData.ts", "src/lib/problemHydration.ts"],
      validationPacks: ["deterministic-core", "artifact-compiler"],
      changeContractId: "change.ontology.lessonArtifactLane",
    },
    {
      id: "seq.problem-content",
      axis: "learning-domain",
      fields: ["problem", "steps", "geometry", "trials", "learn", "approach"],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["ProblemLibrary", "Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "math/teaching content; renderer and effect choices stay outside this lane",
      currentAuthority: ["ontology/data/sequencer.ts", "ontology/data/visual.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/seqDataAuthority.ts", "src/lib/semanticPlan.ts"],
      validationPacks: ["deterministic-core", "artifact-compiler", "semantic-loop"],
      changeContractId: "change.ontology.lessonArtifactLane",
    },
    {
      id: "seq.step-formula-logic",
      axis: "learning-domain",
      fields: ["steps[].formulas", "steps[].domain", "steps[].dataRefs", "steps[].showInterpretation"],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "D/L/A reasoning chain and formula reference topology",
      currentAuthority: ["ontology/data/sequencer.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/seqDataAuthority.ts", "src/lib/semanticPlan.ts", "src/lib/sequenceReducers"],
      validationPacks: ["deterministic-core", "sequence-authoring", "artifact-compiler", "semantic-loop"],
      changeContractId: "change.ontology.lessonArtifactLane",
    },
    {
      id: "seq.teaching-narrative",
      axis: "lesson-artifact",
      fields: ["rewriteHints", "customFrames", "steps[].bridge", "steps[].strategyMeta"],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "teacher-facing explanation sequence; not renderer state",
      currentAuthority: ["ontology/data/sequencer.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/semanticPlan.ts", "src/lib/sequenceReducers"],
      validationPacks: ["deterministic-core", "sequence-authoring", "semantic-loop"],
      changeContractId: "change.ontology.lessonArtifactLane",
    },
    {
      id: "seq.frame-overrides",
      axis: "lesson-artifact",
      fields: [
        "frameOverrides.source",
        "frameOverrides.geo",
        "frameOverrides.formulaRefs",
        "frameOverrides.conditionHighlight",
        "frameOverrides.expressionRefs",
        "frameOverrides.expressionDomainRange",
        "frameOverrides.canvasMode",
        "frameOverrides.segmentSubstitutions",
      ],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "frame-local authoring lane; never global scene topology by accident",
      currentAuthority: ["ontology/data/sequencer.ts", "ontology/capabilities/sequencer.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/sequenceReducers", "src/lib/seqFramesSplit.ts", "src/lib/frameOverridesIntegrity.ts"],
      validationPacks: ["deterministic-core", "sequence-authoring", "presenter-parity"],
      changeContractId: "change.ontology.lessonArtifactLane",
    },
    {
      id: "seq.scope-cascade",
      axis: "lesson-artifact",
      fields: ["globalOverrides", "bandedOverrides", "frameOverrides"],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "frame -> band -> global -> default cascade; bands must not overlap",
      currentAuthority: ["ontology/data/sequencer.ts", "ontology/capabilities/sequencer.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/scopedField.ts", "src/lib/scopedResolvers.ts", "src/lib/sequenceReducers/scope.ts"],
      validationPacks: ["deterministic-core", "sequence-authoring", "ontology-runtime-drift"],
      changeContractId: "change.ontology.lessonArtifactLane",
    },
    {
      id: "seq.rendering-scene",
      axis: "rendering-semantics",
      fields: ["visualComponentsV2", "jsxScene", "auxScenes", "sceneCouplings", "scenes", "v4SceneCouplings"],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "renderer-neutral authored scene semantics; Scene3D remains additive and deferred",
      currentAuthority: ["ontology/data/visual.ts", "ontology/capabilities/scene.ts", "rendering/schema.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/jsxGraphRenderer.ts", "src/lib/jsxGraph/sceneCompiler.ts"],
      validationPacks: ["deterministic-core", "capability-routing", "presenter-parity", "ontology-runtime-drift"],
      changeContractId: "change.ontology.renderingSemantics",
    },
    {
      id: "seq.flow-scene",
      axis: "rendering-semantics",
      fields: ["flowMermaid", "flowFrames"],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "flow visualization semantics; complete per-frame Mermaid definitions only",
      currentAuthority: ["ontology/capabilities/sequencer.ts", "src/types/seq-data.ts"],
      descenders: ["src/lib/flowReducers.ts", "src/components/concept-flow"],
      validationPacks: ["deterministic-core", "sequence-authoring", "presenter-parity"],
      changeContractId: "change.ontology.renderingSemantics",
    },
    {
      id: "seq.semantic-plan",
      axis: "evaluation-lineage",
      fields: ["semanticIntent", "semanticPolicy", "semanticPlan", "semanticIssues"],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "provider-neutral teaching semantics and validation findings",
      currentAuthority: ["ontology/data/sequencer.ts", "src/types/seq-data.ts", "src/lib/semanticPlan.ts"],
      descenders: ["src/lib/problemHydration.ts", "src/lib/localDraftSave.ts", "src/tools/runSemanticLoop.ts"],
      validationPacks: ["deterministic-core", "artifact-compiler", "semantic-loop"],
      changeContractId: "change.ontology.evaluationLineage",
    },
    {
      id: "seq.effect-authoring",
      axis: "effect-semantics",
      fields: ["frameOverrides.effectInline"],
      writerSurfaces: ["Design", "Sequencer"],
      readerSurfaces: ["Design", "Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "HOW-only per-frame per-target effects; no structure or formula mutation",
      currentAuthority: ["ontology/capabilities/sequencer.ts", "ontology/frontend.ts", "src/types/seq-data.ts"],
      descenders: ["src/components/design", "src/components/ui/InlineEffectPopover.tsx", "src/effects"],
      validationPacks: ["deterministic-core", "capability-routing", "presenter-parity"],
      changeContractId: "change.ontology.effectSemantics",
    },
    {
      id: "seq.lineage-feedback",
      axis: "evaluation-lineage",
      fields: ["lineage", "learn", "semanticIssues"],
      writerSurfaces: ["Sequencer", "Presenter"],
      readerSurfaces: ["Sequencer", "Presenter", "PlayBook"],
      durableBoundary: "BackPropagation evidence and semantic-loop findings, not authoring source of truth",
      currentAuthority: ["ontology/data/learn.ts", "ontology/action.ts", "src/types/seq-data.ts"],
      descenders: ["src/tools/runSemanticLoop.ts", "reports/semantic-loop.json", "ontology/runtime.ts"],
      validationPacks: ["deterministic-core", "ontology-runtime-drift", "semantic-loop"],
      changeContractId: "change.ontology.evaluationLineage",
    },
    {
      id: "seq.workbench-authoring",
      axis: "lesson-artifact",
      fields: ["dependencyAtoms", "functionTemplates", "conditionPredicates"],
      writerSurfaces: ["Sequencer"],
      readerSurfaces: ["Sequencer"],
      durableBoundary: "Workbench authoring helpers; optional and zero-impact when absent",
      currentAuthority: ["ontology/data/sequencer.ts", "src/types/seq-data.ts"],
      descenders: ["src/components/sequencer/workbench", "src/lib/conditionMatching"],
      validationPacks: ["deterministic-core", "sequence-authoring", "artifact-compiler"],
      changeContractId: "change.ontology.lessonArtifactLane",
    },
  ],
  projectOntologyScopeRedesign: {
    id: "education-template.project-ontology-scope",
    status: "needs-contract",
    purpose: "Provide a project-scope ontology map before runtime edits in education-oriented projects.",
    nonGoals: [
      "Do not implement 3D runtime in this redesign slice.",
      "Do not widen SceneV4 for future 3D without an approved contract.",
      "Do not turn Save Draft into Cloud publish.",
      "Do not replace generated registries by hand; regenerate descenders.",
    ],
    validationLadder: [
      "bun run resolve:change -- <request>",
      "bun run change:gen",
      "bun run capability:gen when capability ownership changes",
      "bun test tests/changeContracts.test.ts src/lib/changeResolver.test.ts",
      "bun run ontology:drift",
      "bun run ontology:drift:runtime",
      "bun run semantic:loop",
      "Playwright MCP QA when runtime behavior changes",
    ],
  },
};
